const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const KEY='sevilleja_portal_v1';
const seed={posts:[{id:'p1',title:'La primavera vuelve a nuestros caminos',category:'Naturaleza',date:'2026-04-18',excerpt:'Los senderos de La Jara recuperan su color. Una invitación a recorrerlos con calma y descubrir el paisaje que nos rodea.',image:'assets/sevilleja-hero.png'},{id:'p2',title:'Así vivimos la jornada vecinal',category:'Comunidad',date:'2026-05-06',excerpt:'Una mañana para compartir ideas, recuperar tradiciones y seguir construyendo juntos el pueblo que queremos.',image:'assets/sevilleja-hero.png'},{id:'p3',title:'Memoria viva: historias de nuestra gente',category:'Historias',date:'2026-05-22',excerpt:'Conversamos con quienes mejor conocen estas calles para conservar sus recuerdos y hacerlos parte de nuestro futuro.',image:'assets/sevilleja-hero.png'}],events:[{id:'e1',title:'Ruta por los molinos de La Jara',date:'2026-08-15',time:'09:00',place:'Plaza Mayor',description:'Paseo guiado para todas las edades.'},{id:'e2',title:'Noche de música en la plaza',date:'2026-08-22',time:'22:00',place:'Plaza Mayor',description:'Música al aire libre y encuentro vecinal.'},{id:'e3',title:'Taller de memoria y fotografías',date:'2026-09-05',time:'11:00',place:'Centro social',description:'Trae tus fotos antiguas y comparte su historia.'}],signups:[],transactions:[{id:'t1',type:'income',concept:'Aportaciones actividades',amount:2450,date:'2026-03-01'},{id:'t2',type:'income',concept:'Subvención cultural',amount:1800,date:'2026-04-12'},{id:'t3',type:'expense',concept:'Material para talleres',amount:760,date:'2026-04-20'},{id:'t4',type:'expense',concept:'Sonido y escenario',amount:940,date:'2026-05-18'}]};
let data=load(), activeTab='overview', editing=null;
function load(){try{return {...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderPublic();renderAdmin()}
const money=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n);
const dateLong=d=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'));
const escapeHTML=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function renderPublic(){
 $('#blogGrid').innerHTML=data.posts.length?data.posts.map(p=>`<article class="post-card"><div class="post-image"><img src="${p.image||'assets/sevilleja-hero.png'}" alt=""></div><div class="post-body"><div class="post-meta"><span>${escapeHTML(p.category)}</span><span>${dateLong(p.date)}</span></div><h3>${escapeHTML(p.title)}</h3><p>${escapeHTML(p.excerpt)}</p><span class="read-more">LEER HISTORIA →</span></div></article>`).join(''):'<p class="empty">Pronto publicaremos nuevas historias.</p>';
 const months=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];
 const future=[...data.events].sort((a,b)=>a.date.localeCompare(b.date));
 $('#eventsList').innerHTML=future.length?future.map(e=>{const d=new Date(e.date+'T12:00:00');return `<article class="event-row"><div class="event-date"><strong>${String(d.getDate()).padStart(2,'0')}</strong><span>${months[d.getMonth()]}</span></div><div class="event-info"><h3>${escapeHTML(e.title)}</h3><span>${escapeHTML(e.description)}</span></div><div class="event-place"><span>⌖</span><span>${escapeHTML(e.place)} · ${escapeHTML(e.time)} h</span></div><button class="btn btn-cream signup-open" data-id="${e.id}">Quiero apuntarme →</button></article>`}).join(''):'<p class="empty">No hay próximos eventos publicados.</p>';
 const inc=data.transactions.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0), exp=data.transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0), total=inc+exp||1;
 $('#totalIncome').textContent=money(inc);$('#totalExpense').textContent=money(exp);$('#netBalance').textContent=money(inc-exp);$('#incomeBar').style.width=`${inc/total*100}%`;$('#expenseBar').style.width=`${exp/total*100}%`;$('#balanceMessage').textContent=inc>=exp?'El balance se mantiene en positivo. Datos actualizados por la administración.':'Los gastos superan actualmente a los ingresos. Datos actualizados por la administración.';
}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')}
function closeModals(){$$('.modal').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')})}
document.addEventListener('click',e=>{
 if(e.target.closest('[data-close]'))closeModals();
 const signup=e.target.closest('.signup-open');if(signup){const ev=data.events.find(x=>x.id===signup.dataset.id);$('#signupTitle').textContent=ev.title;$('#signupForm').eventId.value=ev.id;openModal('#signupModal')}
 if(e.target.closest('.admin-open'))openModal('#adminModal');
 const tab=e.target.closest('.admin-tab');if(tab){activeTab=tab.dataset.tab;editing=null;$$('.admin-tab').forEach(x=>x.classList.toggle('active',x===tab));renderAdmin()}
 const act=e.target.closest('[data-action]');if(act)handleAdminAction(act.dataset.action,act.dataset.id);
});
$('.menu-toggle').onclick=()=>{const n=$('.main-nav');n.classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',n.classList.contains('open'))};
$$('.main-nav a').forEach(a=>a.onclick=()=>$('.main-nav').classList.remove('open'));
$('#signupForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.signups.push({id:crypto.randomUUID(),eventId:f.get('eventId'),firstName:f.get('firstName').trim(),lastName:f.get('lastName').trim(),birthDate:f.get('birthDate'),createdAt:new Date().toISOString()});save();e.target.reset();closeModals();toast('¡Inscripción confirmada! Nos vemos allí.')};
$('#contactForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Mensaje enviado. Gracias por escribirnos.')};
$('#loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('username')==='admin'&&f.get('password')==='Sevilleja2026'){closeModals();$('#adminPanel').classList.add('open');$('#adminPanel').setAttribute('aria-hidden','false');renderAdmin();e.target.reset()}else toast('Usuario o contraseña incorrectos')};
$('#logoutBtn').onclick=$('#closeAdmin').onclick=()=>{$('#adminPanel').classList.remove('open');$('#adminPanel').setAttribute('aria-hidden','true')};
function renderAdmin(){if(!$('#adminPanel').classList.contains('open'))return;const c=$('#adminContent'), titles={overview:'Resumen general',posts:'Gestionar blog',events:'Gestionar eventos',attendees:'Inscripciones',accounts:'Balance de cuentas'};$('#adminTitle').textContent=titles[activeTab];
 if(activeTab==='overview'){const inc=data.transactions.filter(t=>t.type==='income').reduce((s,t)=>s+ +t.amount,0),exp=data.transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+ +t.amount,0);c.innerHTML=`<section class="admin-dashboard"><div class="admin-stats"><div class="admin-stat"><small>PUBLICACIONES</small><strong>${data.posts.length}</strong></div><div class="admin-stat"><small>PRÓXIMOS EVENTOS</small><strong>${data.events.length}</strong></div><div class="admin-stat"><small>INSCRIPCIONES</small><strong>${data.signups.length}</strong></div><div class="admin-stat"><small>BALANCE</small><strong>${money(inc-exp)}</strong></div></div><div class="admin-grid"><div class="admin-box"><h3>Próximos eventos</h3>${data.events.slice(0,4).map(e=>`<div class="mini-row"><span>${escapeHTML(e.title)}</span><b>${dateLong(e.date)}</b></div>`).join('')||'<p>Sin eventos.</p>'}</div><div class="admin-box"><h3>Últimas inscripciones</h3>${data.signups.slice(-5).reverse().map(s=>`<div class="mini-row"><span>${escapeHTML(s.firstName+' '+s.lastName)}</span><b>${escapeHTML(data.events.find(e=>e.id===s.eventId)?.title||'Evento eliminado')}</b></div>`).join('')||'<p>Todavía no hay inscripciones.</p>'}</div></div></section>`}
 if(activeTab==='posts')renderPosts(c);if(activeTab==='events')renderEvents(c);if(activeTab==='attendees')renderAttendees(c);if(activeTab==='accounts')renderAccounts(c);
}
function renderPosts(c){const p=editing&&data.posts.find(x=>x.id===editing);c.innerHTML=`<div class="admin-section-title"><h3>Publicaciones</h3><button class="btn btn-dark" data-action="new-post">+ Nueva publicación</button></div>${editing==='new'||p?`<form id="postForm" class="admin-form"><h3>${p?'Editar':'Nueva'} publicación</h3><input type="hidden" name="id" value="${p?.id||''}"><div class="form-grid"><label>Título<input required name="title" value="${escapeHTML(p?.title||'')}"></label><label>Categoría<input required name="category" value="${escapeHTML(p?.category||'Actualidad')}"></label></div><label>Fecha<input required type="date" name="date" value="${p?.date||new Date().toISOString().slice(0,10)}"></label><label>Texto<textarea required name="excerpt">${escapeHTML(p?.excerpt||'')}</textarea></label><label>Imagen (opcional)<input type="file" name="image" accept="image/*"></label><div class="form-actions"><button type="button" class="btn btn-outline" data-action="cancel">Cancelar</button><button class="btn btn-dark">Guardar y publicar</button></div></form>`:''}<table class="data-table"><thead><tr><th>TÍTULO</th><th>CATEGORÍA</th><th>FECHA</th><th>ACCIONES</th></tr></thead><tbody>${data.posts.map(x=>`<tr><td><b>${escapeHTML(x.title)}</b></td><td><span class="tag">${escapeHTML(x.category)}</span></td><td>${dateLong(x.date)}</td><td class="actions"><button class="icon-btn" data-action="edit-post" data-id="${x.id}">Editar</button><button class="icon-btn danger" data-action="delete-post" data-id="${x.id}">Eliminar</button></td></tr>`).join('')}</tbody></table>`;const f=$('#postForm');if(f)f.onsubmit=savePost}
function renderEvents(c){const p=editing&&data.events.find(x=>x.id===editing);c.innerHTML=`<div class="admin-section-title"><h3>Eventos</h3><button class="btn btn-dark" data-action="new-event">+ Nuevo evento</button></div>${editing==='new'||p?`<form id="eventForm" class="admin-form"><h3>${p?'Editar':'Nuevo'} evento</h3><input type="hidden" name="id" value="${p?.id||''}"><label>Título<input required name="title" value="${escapeHTML(p?.title||'')}"></label><div class="form-grid"><label>Fecha<input required type="date" name="date" value="${p?.date||''}"></label><label>Hora<input required type="time" name="time" value="${p?.time||''}"></label></div><label>Lugar<input required name="place" value="${escapeHTML(p?.place||'')}"></label><label>Descripción<textarea required name="description">${escapeHTML(p?.description||'')}</textarea></label><div class="form-actions"><button type="button" class="btn btn-outline" data-action="cancel">Cancelar</button><button class="btn btn-dark">Guardar y publicar</button></div></form>`:''}<table class="data-table"><thead><tr><th>EVENTO</th><th>FECHA</th><th>LUGAR</th><th>APUNTADOS</th><th>ACCIONES</th></tr></thead><tbody>${data.events.map(x=>`<tr><td><b>${escapeHTML(x.title)}</b></td><td>${dateLong(x.date)} · ${x.time}</td><td>${escapeHTML(x.place)}</td><td>${data.signups.filter(s=>s.eventId===x.id).length}</td><td class="actions"><button class="icon-btn" data-action="edit-event" data-id="${x.id}">Editar</button><button class="icon-btn danger" data-action="delete-event" data-id="${x.id}">Eliminar</button></td></tr>`).join('')}</tbody></table>`;const f=$('#eventForm');if(f)f.onsubmit=saveEvent}
function renderAttendees(c){c.innerHTML=`<div class="admin-section-title"><h3>Personas inscritas</h3><button class="btn btn-dark" data-action="export">Descargar listado CSV ↓</button></div><table class="data-table"><thead><tr><th>EVENTO</th><th>NOMBRE Y APELLIDOS</th><th>FECHA DE NACIMIENTO</th><th>INSCRIPCIÓN</th><th></th></tr></thead><tbody>${data.signups.map(s=>`<tr><td>${escapeHTML(data.events.find(e=>e.id===s.eventId)?.title||'Evento eliminado')}</td><td><b>${escapeHTML(s.firstName+' '+s.lastName)}</b></td><td>${dateLong(s.birthDate)}</td><td>${new Date(s.createdAt).toLocaleDateString('es-ES')}</td><td><button class="icon-btn danger" data-action="delete-signup" data-id="${s.id}">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="5">Todavía no hay inscripciones.</td></tr>'}</tbody></table>`}
function renderAccounts(c){const inc=data.transactions.filter(t=>t.type==='income').reduce((s,t)=>s+ +t.amount,0),exp=data.transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+ +t.amount,0);c.innerHTML=`<div class="admin-section-title"><h3>Ingresos y gastos</h3><button class="btn btn-dark" data-action="new-transaction">+ Añadir movimiento</button></div><div class="admin-stats"><div class="admin-stat"><small>INGRESOS</small><strong class="amount-income">${money(inc)}</strong></div><div class="admin-stat"><small>GASTOS</small><strong class="amount-expense">${money(exp)}</strong></div><div class="admin-stat"><small>BALANCE</small><strong>${money(inc-exp)}</strong></div></div>${editing==='new'?`<form id="transactionForm" class="admin-form"><h3>Nuevo movimiento</h3><div class="form-grid"><label>Tipo<select name="type"><option value="income">Ingreso</option><option value="expense">Gasto</option></select></label><label>Importe (€)<input required type="number" min="0.01" step="0.01" name="amount"></label></div><label>Concepto<input required name="concept"></label><label>Fecha<input required type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></label><div class="form-actions"><button type="button" class="btn btn-outline" data-action="cancel">Cancelar</button><button class="btn btn-dark">Guardar movimiento</button></div></form>`:''}<table class="data-table"><thead><tr><th>FECHA</th><th>CONCEPTO</th><th>TIPO</th><th>IMPORTE</th><th></th></tr></thead><tbody>${[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<tr><td>${dateLong(t.date)}</td><td><b>${escapeHTML(t.concept)}</b></td><td>${t.type==='income'?'Ingreso':'Gasto'}</td><td class="amount-${t.type}">${t.type==='income'?'+':'−'} ${money(t.amount)}</td><td><button class="icon-btn danger" data-action="delete-transaction" data-id="${t.id}">Eliminar</button></td></tr>`).join('')}</tbody></table>`;const f=$('#transactionForm');if(f)f.onsubmit=saveTransaction}
function handleAdminAction(action,id){if(action==='cancel'){editing=null;renderAdmin()}if(action==='new-post'||action==='new-event'||action==='new-transaction'){editing='new';renderAdmin()}if(action==='edit-post'||action==='edit-event'){editing=id;renderAdmin()}if(action.startsWith('delete-')&&confirm('¿Seguro que quieres eliminar este elemento?')){const map={'delete-post':'posts','delete-event':'events','delete-signup':'signups','delete-transaction':'transactions'};data[map[action]]=data[map[action]].filter(x=>x.id!==id);save();toast('Elemento eliminado')}if(action==='export')exportCSV()}
async function savePost(e){e.preventDefault();const f=new FormData(e.target),old=data.posts.find(x=>x.id===f.get('id')),file=f.get('image');let image=old?.image||'assets/sevilleja-hero.png';if(file?.size)image=await fileToData(file);const item={id:old?.id||crypto.randomUUID(),title:f.get('title').trim(),category:f.get('category').trim(),date:f.get('date'),excerpt:f.get('excerpt').trim(),image};data.posts=old?data.posts.map(x=>x.id===old.id?item:x):[item,...data.posts];editing=null;save();toast('Publicación guardada')}
function saveEvent(e){e.preventDefault();const f=new FormData(e.target),old=data.events.find(x=>x.id===f.get('id')),item={id:old?.id||crypto.randomUUID(),title:f.get('title').trim(),date:f.get('date'),time:f.get('time'),place:f.get('place').trim(),description:f.get('description').trim()};data.events=old?data.events.map(x=>x.id===old.id?item:x):[...data.events,item];editing=null;save();toast('Evento guardado')}
function saveTransaction(e){e.preventDefault();const f=new FormData(e.target);data.transactions.push({id:crypto.randomUUID(),type:f.get('type'),amount:Number(f.get('amount')),concept:f.get('concept').trim(),date:f.get('date')});editing=null;save();toast('Movimiento guardado')}
const fileToData=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});
function exportCSV(){const rows=[['Evento','Nombre','Apellidos','Fecha de nacimiento','Fecha de inscripción'],...data.signups.map(s=>[data.events.find(e=>e.id===s.eventId)?.title||'Evento eliminado',s.firstName,s.lastName,s.birthDate,s.createdAt])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='inscripciones-sevilleja.csv';a.click();URL.revokeObjectURL(a.href);toast('Listado descargado')}
$('#year').textContent=new Date().getFullYear();renderPublic();
